paths:
  /api/products/:
    get:
      summary: Obtener todos los Productos
      tags:
        - Productos
      responses:
      "200":
        description: Todos los productos obtenidos correctamente
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#components/schemas/Product"
      "401":
        description: Error por falta de permisos
      "500"
        description: Error interno de el servidor
    post:
      summary: Crear Producto
      tags:
        - Productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#components/requestBodies/UpdateProduct"
      responses:
        "200":
          description: Todos los productos obtenidos correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  payload:
                    $ref: "#components/schemas/Product"
      "401":
        description: Error por falta de permisos
      "500"
        description: Error interno de el servidor


components:
  schema:
    requestBodies:
      UpdateProduct:
        type: object
        properties:
          _id:
            type: ObjectI
            description: id del producto autogenerado por la base de dato
          title: 
            type: string
            description: Nombre del producto
          price:
            type: number
            description: Precio del producto
          code:
            type: string
            description: Codigo del producto
          stock: 
            type: number
            description: Cantidad de producto
          category:
            type: string
            description: Categoria del producto